// Mock data store for the application
export const mockUsers = [
  {
    id: "user-customer-demo-com",
    email: "customer@demo.com",
    password: "password123",
    full_name: "Demo Customer",
    user_type: "customer",
    service_type: null,
    phone: "1234567890",
    address: "123 Demo Street, Demo City",
    created_at: "2023-01-01T00:00:00.000Z",
  },
  {
    id: "user-electrician-demo-com",
    email: "electrician@demo.com",
    password: "password123",
    full_name: "Demo Electrician",
    user_type: "provider",
    service_type: "electrician",
    phone: "1234567891",
    address: "456 Service Ave, Demo City",
    created_at: "2023-01-01T00:00:00.000Z",
  },
  {
    id: "user-plumber-demo-com",
    email: "plumber@demo.com",
    password: "password123",
    full_name: "Demo Plumber",
    user_type: "provider",
    service_type: "plumber",
    phone: "1234567892",
    address: "789 Repair Rd, Demo City",
    created_at: "2023-01-01T00:00:00.000Z",
  },
  {
    id: "admin-demo",
    email: "admin@demo.com",
    password: "password123",
    full_name: "Demo Admin",
    user_type: "admin",
    created_at: "2023-01-01T00:00:00.000Z",
  },
]

export const mockServiceRequests = [
  {
    id: "req-1",
    customer_id: "user-customer-demo-com",
    service_type: "electrician",
    problem_description: "Power outage in my apartment. Need urgent help!",
    preferred_date: "2023-12-25",
    preferred_time: "10:00 AM",
    customer_address: "123 Demo Street, Apt 4B, Demo City",
    status: "pending",
    created_at: "2023-12-20T10:30:00.000Z",
  },
  {
    id: "req-2",
    customer_id: "user-customer-demo-com",
    service_type: "electrician",
    problem_description: "Need to install new ceiling fan in living room",
    preferred_date: "2023-12-26",
    preferred_time: "2:00 PM",
    customer_address: "123 Demo Street, Apt 4B, Demo City",
    status: "payment_pending",
    created_at: "2023-12-19T14:45:00.000Z",
  },
  {
    id: "req-3",
    customer_id: "user-customer-demo-com",
    service_type: "electrician",
    problem_description: "Short circuit in kitchen, sparks coming from outlet",
    preferred_date: "2023-12-27",
    preferred_time: "11:30 AM",
    customer_address: "123 Demo Street, Apt 4B, Demo City",
    status: "in_progress",
    created_at: "2023-12-18T09:15:00.000Z",
  },
]
